<section>
    <h3 class="center-align teal-text text-darken-3">Log In</h3>
    <form action="<?= $requestUrl ?>/user/login" method="POST">
        <fieldset>
            <div class="row">
                <div class="input-field col s12">
                    <input id="email" type="email" class"validate" name="email" /> 
                    <label for="email">Email</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                  <input id="password" type="password" class="validate" name="password"/>
                  <label for="password">Password</label>
                </div>
            </div>
        </fieldset>
        <div class="center-align">
            <button class="center-align teal darken-3 btn waves-effect waves-light" type="submit">Log In</button>
        </div>
    </form>
</section>
    
    
    
    
    
    
    
    
    
    
    
    
</section>