<section>
    
    <h3 class="center-align teal-text text-darken-3">
        <i class="fa fa-unlock-alt" aria-hidden="true"></i>
        Log In
    </h3>

    <form action="<?= $requestUrl ?>/user/login" method="POST">
        <div id="error-message" class="hidden red-text center-align">
    		<h5><i class="fa fa-warning"></i> There are <em id="total-error-count">x</em> error(s) in the form !</h5>
    		
    	</div>
    	<p id="error" class="red-text"><?= $errorMessage ?></p>
        <fieldset>
            <p class="center-align">Authentication informations</p>
            <div class="row">
                <div class="input-field col s12">
                    <input id="email" type="email" class"validate" name="email" value="<?= $email ?>" data-required data-name="Email" /> 
                    <label for="email"  data-error="wrong" data-success="right">Email</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                  <input id="password" type="password"  name="password" data-required data-name="Password" />
                  <label for="password">Password</label>
                </div>
            </div>
        </fieldset>
        
        <div class="center-align">
            <button class="center-align teal darken-3 btn waves-effect waves-light" type="submit">Log In</button>
            <a href="<?= $requestUrl ?>" class="center-align teal darken-3 btn waves-effect waves-light">Cancel</a>
        </div>
    </form>
    
    
    
</section>