<section>
<h3 class="teal-text text-darken-3 center-align"><i class="fa fa-user-plus" aria-hidden="true"></i>
 Create a new account </h3>
 
<form action="<?= $requestUrl ?>/user" method="POST">
    <p class="center-align">Identity and address :</p>
    <div class="row">
        <div class="input-field col s6">
          <input id="first_name" type="text" class="validate" name="firstname" value="<?= $firstname ?>">
          <label for="first_name">First Name</label>
        </div>
        <div class="input-field col s6">
          <input id="last_name" type="text" class="validate" name="lastname" value="<?= $lastname ?>">
          <label for="last_name">Last Name</label>
        </div>
      </div>
      <div class="input-field col s12">
          <small>Birthdate :</small>
          <input id="date" type="date" class="datepicker" name="birthdate" value="<?= $birthdate ?>">
          
      </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="address" type="text" class="validate" name="address" value="<?= $address ?>">
          <label for="address">Address</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s4">
          <input id="city" type="text" class="validate" name="city" value="<?= $city ?>">
          <label for="city">City</label>
        </div>
        <div class="input-field col s4">
          <input id="zip" type="text" class="validate" name="zip" value="<?= $zip ?>">
          <label for="zip">Zip Code</label>
        </div>
        <div class="input-field col s4">
          <input id="phone" type="tel" class="validate" name="phone" value="<?= $phone ?>">
          <label for="phone">Phone number</label>
        </div>
      </div>
     
      <h5 class="center-align red-text text-darken-4"><strong><?= $errorMessage ?></strong></h5>
      
      <p class="center-align">Authentification informations :</p>
      <div class="row">
        <div class="input-field col s12">
          <input id="email" type="email" class="validate" name="mail" value="<?= $mail ?>">
          <label for="email">Email</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="password" type="password" name="password">
          <label for="password">Password</label>
        </div>
      </div>
      <div class="center-align">
          <button  class="waves-effect waves-light btn" type="submit" value="Submit">Submit</button>
          <a href="index" class="waves-effect waves-light btn">Cancel</a>
      </div>
    
</form>
</section>
