<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Ocho Ristorante</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    

    <!-- Librairie jQuery -->
    <script
			  src="https://code.jquery.com/jquery-3.1.1.min.js"
			  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
			  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
    

    <!-- Librairies JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1 class="center-align">
        <a class='red-text text-darken-4' href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logoR.png" height="63" width="57" alt="3WA Restaurant">Ocho  Ristorante 
        </a>
    </h1>
    <!-- Interface utilisateur -->
    <nav class="grey lighten-2 sticky">
        <div class="row">
        <div class="nav-wrapper">
          <a href="#" class="brand-logo center"></a>
          <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
          <ul class="center hide-on-med-and-down container">
            <li><a href="#">HOME</a></li>
            <li><a href="#">MENU</a></li>
            <li><a href="#">RESERVATION</a></li>
            <li><a href="#">ORDER NOW</a></li>
            <li><a href="#">CONTACT</a></li>
            
          </ul>
          <a href="<?= $requestUrl ?>/user" class="red accent-4 right waves-effect waves-light btn-large">SIGN UP</a>
          <a href="<?= $requestUrl ?>/user/login" class="teal accent-4 right waves-effect waves-light btn-large">LOG IN</a>
          <!--<ul id="mobile-demo" class="side-nav">
            <li><a href="#">HOME</a></li>
            <li><a href="#">ORDER NOW</a></li>
            <li><a href="#">LOG IN</a></li>
          </ul>-->
        </div>
        </div>
    </nav>
    
    
  </nav>
</header>




<main class="container">
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer class="page-footer grey lighten-2">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="red-text text-darken-4">Website in development ...</h5>
                <p class="red-text text-darken-4"></p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="red-text text-darken-4">Follow us :</h5>
                <ul>
                    <li>
                        <a href="#!">
                        <i class="fa fa-facebook-official" aria-hidden="true"></i>
                        FaceBook</a></li>
                    <li>
                      <a href="#!">
                          <i class="fa fa-twitter-square" aria-hidden="true"></i>
                          Twitter</a>
                    
                    </li>
                    <li><a href="#!">
                      <i class="fa fa-instagram" aria-hidden="true"></i>
                        Instagram</a>
                    </li>
                </ul>
                
                
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container red-text text-darken-4">
            © 2016 Copyright DUSCH EWEN
            <a class="right" href="#!">
                <ul class="link-list">
                    <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
                    <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
                    <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
                </ul>
            </a>
            </div>
          </div>
        </footer>
<!-- Code principal JavaScript de l'application -->
<script type="text/javascript">
$(document).ready(function(){
$('.carousel').carousel();});
$(".button-collapse").sideNav();	
jQuery(function($){
$(document).ready(function(){
$(function(){
$(window).scroll(function(){
var scroll = $(window).scrollTop();
if (scroll >= 280){
$(".sticky").addClass('smaller');
} else { $(".sticky").removeClass("smaller");} 
}); }); }); }); 
//$('#textarea1').val('Your message');
$('#textarea1').trigger('autoresize');
</script>
<script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>