<section>
    <h3 class="center-align red-text text-darken-4">
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            Order now !
    </h3>

   
        <form id="order-form" action="<?= $requestUrl ?>/order" method="POST">
            <fieldset>
             <h5 class="center-align indigo-text">
                <i class="fa fa-plus" aria-hidden="true"></i>
                 Add Products
            </h5>
            
                <div class="input-field col s12">
                    <select id="meal" name="meal">
                        <option value="" disabled selected>Choose your product</option>
                      <?php foreach($meals as $meal): ?>
                          <option value="<?= $meal['Id'] ?>"><?= $meal['Name'] ?></option>
                      <?php endforeach; ?>
                    </select>
                </div>
                <!-- Meal details box start here -->
                
                <div class="row center-align">
                    <div class="col s12 m6 offset-m3">
                      <div class="card hidden center-align" id="meal-details">
                        <div class="card-image">
                          <img src="" alt="Product Picture">
                          <span class="card-title black-text">Card Title</span>
                        </div>
                        <div class="card-content">
                          <p>I am a very simple card. I am good at containing small bits of information.
                          I am convenient because I require little markup to use effectively.</p>
                        </div>
                        <div class="card-action">
                          <a class="red-text text-darken-4" href="#">This is a link</a>
                        </div>
                      </div>
                    </div>
                </div>
                <input type="hidden" id="salePrice" name="salePrice" value=""/>
                
                <div class="input-field col s6">
                    <input type="text" name="quantity" id="quantity"/>
                    <label for="quantity">Quantity</label>
                </div>
            
            <div class="center-align">
                <button type="button" id="addtobasket" class="indigo waves-effect waves-light btn">Add</button>
            </div>
            </fieldset>
            <fieldset class="hidden" id="showonclick">
                 <h5 class="center-align indigo-text">
                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                 Your Basket
                </h5>
                <section id="order-summary"></section>
                
               
                
                
                
                
            </fieldset>
            <div class="center-align">
                <button type="submit" class="indigo waves-effect waves-light btn">CONFIRM ORDER</button>
                <a href="<?= $requestUrl ?>" class="red darken-4 waves-effect waves-light btn">Cancel</a>
            </div>
        </form>
</section>
<script src="<?= $wwwUrl ?>/js/classes/BasketSession.class.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/OrderForm.class.js"></script>
    
    


